# Infrastructure
kotlinVersion=2.3.0
appVersion=1.2.2

# Core Dependencies
ktorVersion=3.3.3
koinVersion=3.5.3
serializationVersion=1.8.0

# Performance
org.gradle.jvmargs=-Xmx4g -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
