package hivens.launcher.component

import hivens.core.api.interfaces.IManifestProcessorService
import hivens.core.data.FileManifest
import org.slf4j.LoggerFactory
import java.io.File
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import kotlin.io.path.exists
import kotlin.io.path.isRegularFile
import kotlin.io.path.name

/**
 * Component responsible for assembling the classpath for launching the JVM.
 * Filters unnecessary files (configs, natives, mods) so that the local hash matches the server hash.
 *
 * @param osName the current OS as reported by `os.name`. Defaulted to the
 *        runtime property; tests inject a fixed value to verify wrong-OS
 *        native filtering (#157).
 */
class ClasspathProvider(
    private val manifestProcessor: IManifestProcessorService,
    osName: String = System.getProperty("os.name", ""),
) {

    private val logger = LoggerFactory.getLogger(ClasspathProvider::class.java)

    // Files that are generated by the launcher but should not end up in the classpath
    private val internalBlacklist = setOf("extra.zip", "assets.zip", "natives.zip")

    /**
     * The Maven-Central native classifier suffixes for OSes that AREN'T this
     * one. Used to filter out wrong-platform native JARs the server ships
     * unconditionally -- `*-natives-windows.jar` on Linux, `*-natives-linux.jar`
     * on macOS, etc. Both the modern (`macos`) and legacy LWJGL2 (`osx`)
     * macOS classifiers are listed; only the matching subset gets dropped.
     *
     * Computed once at construction so the per-jar filter is a single
     * `Set.any` lookup, not a per-call OS sniff.
     */
    private val foreignNativeSuffixes: Set<String> = run {
        val lower = osName.lowercase()
        val all = setOf("linux", "windows", "macos", "osx")
        when {
            lower.contains("linux")   -> all - setOf("linux")
            lower.contains("windows") -> all - setOf("windows")
            lower.contains("mac") || lower.contains("darwin") -> all - setOf("macos", "osx")
            else -> emptySet()  // Unknown OS -- drop nothing rather than risk
                                // stripping the platform's own native and
                                // crashing on launch with no recourse.
        }
    }

    fun buildClasspath(
        clientRoot: Path,
        manifest: FileManifest,
        excludedModules: List<String>
    ): String {
        val allJars = LinkedHashSet<Path>()

        val modsDir = clientRoot.resolve("mods").toAbsolutePath()
        val libDir = clientRoot.resolve("libraries").toAbsolutePath()

        // 1. Take paths from the manifest (Main source)
        val flatManifest = manifestProcessor.flattenManifest(manifest)
        flatManifest.keys.forEach { rawPath ->
            val resolved = resolveSanitizedPath(clientRoot, rawPath)
            allJars.add(resolved)
        }

        // 2. Fallback: Local scan (if manifest is empty or old server)
        if (manifest.files.isEmpty() && manifest.directories.isEmpty()) {
            val before = allJars.size
            runCatching {
                if (!Files.exists(libDir)) {
                    logger.warn("Empty manifest and no local libraries dir at {} -- classpath will be empty", libDir)
                } else {
                    Files.walk(libDir).use { stream ->
                        stream.filter { path ->
                            val name = path.name.lowercase()
                            path.isRegularFile() && name.endsWith(".jar") && !name.endsWith(".cache")
                        }.forEach { allJars.add(it) }
                    }
                    logger.info("Empty manifest fallback: walked {} and found {} JARs", libDir, allJars.size - before)
                }
            }.onFailure { e ->
                logger.warn("Local library scan failed at {}: {}", libDir, e.message, e)
            }
        }

        // Preparing exceptions (normalizing paths)
        // excludedModules can come as filenames or paths
        val absoluteExcludedNames = excludedModules.map { Paths.get(it).name.lowercase() }.toSet()

        // 3. Filtering and Sorting
        return allJars
            .asSequence()
            .map { it.toAbsolutePath() }
            .filter { path ->
                validateLibrary(path, modsDir, absoluteExcludedNames)
            }
            // Sorting is important! If the order is different, the hash will be different.
            .sortedWith(::compareLibraries)
            .map { it.toString() }
            .joinToString(File.pathSeparator)
    }

    /**
     * Checks if the library is suitable for inclusion in the classpath.
     */
    private fun validateLibrary(path: Path, modsDir: Path, excludedNames: Set<String>): Boolean {
        val fileName = path.name.lowercase()

        // 1. Existence check
        if (!path.exists()) {
            // If this is a library, but it is not on the disk, this is a problem, but you cannot add a non-existent path
            if (path.toString().contains("libraries")) {
                logger.warn("Library missing from manifest: $path")
            }
            return false
        }

        // 2. JAR and ZIP only
        if (!fileName.endsWith(".jar") && !fileName.endsWith(".zip")) return false

        // 3. Exclude the mods folder and system folders (config, assets)
        if (path.startsWith(modsDir)) return false

        for (part in path) {
            val n = part.name
            if (n == "config" || n == "assets") return false
        }

        // 4. Explicit exceptions (optional mods)
        if (excludedNames.contains(fileName)) return false

        // 5. Internal blacklist (extra.zip, etc.)
        if (internalBlacklist.contains(fileName)) return false
        if ((fileName.startsWith("assets-") || fileName.startsWith("natives-")) && fileName.endsWith(".zip")) {
            return false
        }

        // 6. Wrong-OS native JARs (#157). Server-side manifests ship every
        // platform's native classifier ("…-natives-windows.jar",
        // "…-natives-linux.jar", "…-natives-macos.jar") to every client by
        // default. Loading the wrong-platform jar onto the classpath either
        // wastes a few MB of RAM (best case) or raises UnsatisfiedLinkError
        // when the JVM tries to dlopen a Mach-O on Linux. Drop anything
        // matching another platform's classifier; keep our own.
        if (fileName.endsWith(".jar")) {
            val withoutExt = fileName.removeSuffix(".jar")
            for (suffix in foreignNativeSuffixes) {
                if (withoutExt.endsWith("-natives-$suffix")) return false
            }
        }

        val normalizedPath = path.toString().replace("\\", "/")

        if (normalizedPath.contains("/net/minecraft/client/") && fileName.startsWith("client-")) {
            return false
        }

        if (normalizedPath.contains("/net/minecraftforge/") && fileName.contains("srgutils")) {
            return false
        }

        return true
    }

    /**
     * Resolves the path from the manifest relative to the client root.
     * Removes the prefix with the server name, if any (Legacy Smarty structure).
     */
    private fun resolveSanitizedPath(root: Path, rawPath: String): Path {
        val pathPart = Paths.get(rawPath)

        // Logic for removing the prefix (server name) if it is in the manifest path
        // Example: "Nevermine/libraries/..." -> "libraries/..."
        if (pathPart.nameCount > 1) {
            val first = pathPart.getName(0).toString()
            if (!first.startsWith("libraries") && first != "bin" && first != "mods") {
                return root.resolve(pathPart.subpath(1, pathPart.nameCount))
            }
        }
        return root.resolve(pathPart)
    }

    /**
     * Sorting for deterministic load order.
     * LaunchWrapper and Bootstrap should come first.
     */
    private fun compareLibraries(p1: Path, p2: Path): Int {
        val n1 = p1.name.lowercase()
        val n2 = p2.name.lowercase()

        val p1Priority = isBootstrapLibrary(n1)
        val p2Priority = isBootstrapLibrary(n2)

        return when {
            p1Priority && !p2Priority -> -1
            !p1Priority && p2Priority -> 1
            else -> p1.compareTo(p2) // Alphabetical order for the rest
        }
    }

    private fun isBootstrapLibrary(name: String): Boolean {
        return name.contains("launchwrapper") ||
                name.contains("bootstraplauncher") ||
                name.contains("asm-all")
    }
}
