#!/usr/bin/env python3
"""Regenerate the bundled Material Symbols icon set for Nexira.

Reads tools/icons/icons.txt and writes:
  - client-ui/src/desktopMain/kotlin/hivens/ui/icons/NxIcon.kt   (typed codepoint catalog)
  - client-ui/src/commonMain/composeResources/font/material_symbols.ttf   (subset)

Icons are rendered by codepoint (not ligature), so the font is subset with
--unicodes to exactly the listed glyphs -- it carries only what the app uses.
The variable axes (FILL, wght, opsz, GRAD) are kept so Symbol() can fill/weight.

Adding an icon = add a line to icons.txt and run this script, then reference
NxIcon.<Name>. Normal builds do not need this script -- the outputs are committed.

Requires: Python fontTools (pyftsubset) and the Material Symbols Rounded variable
font installed locally (Arch: ttf-material-symbols-variable).
"""
import os
import re
import subprocess
import sys

from fontTools.ttLib import TTFont

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MANIFEST = os.path.join(ROOT, "tools", "icons", "icons.txt")
KT_OUT = os.path.join(ROOT, "client-ui", "src", "desktopMain", "kotlin", "hivens", "ui", "icons", "NxIcon.kt")
FONT_OUT = os.path.join(ROOT, "client-ui", "src", "commonMain", "composeResources", "font", "material_symbols.ttf")

FONT_CANDIDATES = [
    "/usr/share/fonts/ttf-material-symbols-variable/MaterialSymbolsRounded[FILL,GRAD,opsz,wght].ttf",
    os.path.expanduser("~/.local/share/fonts/material-symbols/MaterialSymbolsRounded[FILL,GRAD,opsz,wght].ttf"),
]


def snake(name):
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name)
    s = re.sub(r"(?<=[a-zA-Z])(?=[0-9])", "_", s)
    return s.lower()


def read_manifest():
    entries = []
    with open(MANIFEST, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            name, lig = (p.strip() for p in line.split("=", 1)) if "=" in line else (line, snake(line))
            entries.append((name, lig))
    entries.sort()
    return entries


def find_source_font():
    for p in FONT_CANDIDATES:
        if os.path.isfile(p):
            return p
    sys.exit("Material Symbols Rounded variable font not found; install ttf-material-symbols-variable.")


def main():
    entries = read_manifest()
    src = find_source_font()

    # ligature (== glyph name) -> codepoint, via the source cmap
    name_to_cp = {}
    for cp, gname in TTFont(src).getBestCmap().items():
        name_to_cp.setdefault(gname, cp)

    resolved = []  # (PascalName, codepoint)
    missing = []
    for name, lig in entries:
        cp = name_to_cp.get(lig)
        (resolved if cp is not None else missing).append((name, cp if cp is not None else lig))
    if missing:
        sys.exit("No codepoint for: " + ", ".join(f"{n} ({l})" for n, l in missing))

    # NxIcon.kt
    lines = [
        "// Generated by tools/icons/regenerate.py -- do not edit by hand.",
        "// Each entry is a Material Symbols codepoint, rendered via Symbol(NxIcon.X).",
        "package hivens.ui.icons",
        "",
        "/** Material Symbols glyphs bundled in the app. Add to tools/icons/icons.txt and regenerate. */",
        "object NxIcon {",
    ]
    lines += [f"    val {name} = IconKey(0x{cp:04x})" for name, cp in resolved]
    lines.append("}")
    os.makedirs(os.path.dirname(KT_OUT), exist_ok=True)
    with open(KT_OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    # subset by codepoint; drop OpenType layout (we render by codepoint), keep axes
    codepoints = sorted({cp for _, cp in resolved})
    os.makedirs(os.path.dirname(FONT_OUT), exist_ok=True)
    subprocess.run(
        [
            "pyftsubset", src,
            "--unicodes=" + ",".join(f"U+{cp:04X}" for cp in codepoints),
            "--layout-features=",
            "--output-file=" + FONT_OUT,
        ],
        check=True,
    )
    print(f"icons: {len(resolved)}   distinct glyphs: {len(codepoints)}")
    print(f"catalog: {os.path.relpath(KT_OUT, ROOT)}")
    print(f"font:    {os.path.relpath(FONT_OUT, ROOT)}  ({os.path.getsize(FONT_OUT) // 1024} KB)")


if __name__ == "__main__":
    main()
