package hivens.packaging

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

/**
 * Emits a shell-sourceable fragment with the jlink module list + flag set,
 * so `scripts/build-appimage.sh` can read them from the same configuration
 * that the gradle-side [CustomRuntimeTask] consumes. Eliminates the
 * hardcoded copy of the same lists that previously lived inline in the
 * shell script.
 *
 * Generated file shape:
 *
 * ```sh
 * # Generated by :client-ui:emitAppImageProfile -- do not edit.
 * # Sourced by scripts/build-appimage.sh to keep one source of truth
 * # between gradle's customRuntime task and the AppImage jlink call.
 *
 * NEXIRA_JLINK_MODULES="java.base,java.desktop,..."
 * NEXIRA_JLINK_OPTIONS=(
 *     --strip-debug
 *     --no-header-files
 *     --no-man-pages
 *     --compress=zip-9
 *     --vm=server
 *     --include-locales=en,ru,de
 * )
 * NEXIRA_GENERATE_CDS=1
 * NEXIRA_JVM_MODULE_OPTIONS=(
 *     --add-opens=java.desktop/sun.awt.X11=ALL-UNNAMED
 *     --enable-native-access=ALL-UNNAMED
 * )
 * ```
 *
 * Bash array form (rather than space-joined string) is deliberate: it
 * preserves flag-equals-value tokens like `--compress=zip-9` as a single
 * argv element even if jlink ever gains a flag whose value contains
 * whitespace. The shell script unpacks with `"${NEXIRA_JLINK_OPTIONS[@]}"`.
 *
 * `NEXIRA_JVM_MODULE_OPTIONS` is consumed twice by the script -- once to dump
 * the base CDS archive, once to write the AppRun launch line -- which is the
 * point: [ModuleSystemArgs] explains why those two have to be the same set.
 *
 * Inputs are the same `Property` values that [CustomRuntimeTask] reads
 * from [PackagingExtension]. UP-TO-DATE works for free; the script only
 * regenerates when a flag actually changes.
 */
@CacheableTask
abstract class EmitAppImageProfileTask : DefaultTask() {

    // ── Inputs (mirror CustomRuntimeTask) ─────────────────────────────────

    @get:Input
    abstract val modules: ListProperty<String>

    @get:Input
    abstract val stripDebug: Property<Boolean>

    @get:Input
    abstract val noHeaderFiles: Property<Boolean>

    @get:Input
    abstract val noManPages: Property<Boolean>

    @get:Input
    @get:Optional
    abstract val compress: Property<String>

    @get:Input
    @get:Optional
    abstract val vmKind: Property<String>

    @get:Input
    @get:Optional
    abstract val includeLocales: Property<String>

    /** Base CDS archive; see [hivens.packaging.JlinkOptionsExtension]. */
    @get:Input
    abstract val generateCdsArchive: Property<Boolean>

    /** Module-system flags for the CDS dump and the AppRun launch line; see [ModuleSystemArgs]. */
    @get:Input
    abstract val cdsDumpArgs: ListProperty<String>

    // ── Output ────────────────────────────────────────────────────────────

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    // ── Action ────────────────────────────────────────────────────────────

    @TaskAction
    fun emit() {
        val flags = buildList {
            if (stripDebug.get()) add("--strip-debug")
            if (noHeaderFiles.get()) add("--no-header-files")
            if (noManPages.get()) add("--no-man-pages")
            compress.orNull?.let { add("--compress=$it") }
            vmKind.orNull?.let { add("--vm=$it") }
            includeLocales.orNull?.let { add("--include-locales=$it") }
        }
        val moduleList = modules.get().joinToString(",")
        val file = outputFile.get().asFile
        file.parentFile.mkdirs()
        file.writeText(buildString {
            append("# Generated by :client-ui:emitAppImageProfile -- do not edit.\n")
            append("# Sourced by scripts/build-appimage.sh to keep one source of\n")
            append("# truth between gradle's customRuntime task and the AppImage\n")
            append("# jlink call. Edits go to the packaging { } block in\n")
            append("# client-ui/build.gradle.kts.\n")
            append("\n")
            append("NEXIRA_JLINK_MODULES=\"").append(moduleList).append("\"\n")
            append("NEXIRA_JLINK_OPTIONS=(\n")
            for (flag in flags) {
                append("    ").append(flag).append("\n")
            }
            append(")\n")
            append("NEXIRA_GENERATE_CDS=").append(if (generateCdsArchive.get()) "1" else "0").append("\n")
            append("NEXIRA_JVM_MODULE_OPTIONS=(\n")
            for (flag in cdsDumpArgs.get()) {
                append("    ").append(flag).append("\n")
            }
            append(")\n")
        })
    }
}
