#!/usr/bin/env python3
# Scans source files for documentation anti-patterns banned under Style D
# (see ~/.claude/.../memory/feedback_documentation_style_d.md).
#
# Catches the mechanical / process-metadata violations that are objectively
# wrong in any reasonable style. Semantic violations (KDoc bloat on
# private symbols, names not doing the work) need human review.

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

SCAN_EXTS = {".kt", ".kts", ".java"}
SCAN_DIRS = ["client-config", "client-core", "client-launcher", "client-ui", "buildSrc"]

EXCLUDE_PATH_FRAGMENTS = ("/build/", "/.gradle/", "/.idea/")


@dataclass(frozen=True)
class Rule:
    name: str
    pattern: re.Pattern[str]
    explanation: str


# Each pattern intentionally narrow to avoid false positives. A comment line
# is anything matching `^\s*(//|\*|/\*\*?)` followed by suspect content.
COMMENT_PREFIX = r"^\s*(?://|\*|/\*\*?)"

RULES: list[Rule] = [
    Rule(
        name="pr-number",
        pattern=re.compile(rf"{COMMENT_PREFIX}.*\bPR #\d+\b"),
        explanation="PR number reference in comment (Style D: git blame carries this).",
    ),
    Rule(
        name="issue-ref-paren",
        # `(#123)` style GitHub issue/PR references. All-digits inside the
        # parens distinguishes from hex color literals like `(#FFFFFF)`.
        pattern=re.compile(rf"{COMMENT_PREFIX}.*\(#\d+\)"),
        explanation="Parenthesized issue/PR ref in comment (Style D: PR body carries this).",
    ),
    Rule(
        name="codex-marker",
        pattern=re.compile(rf"{COMMENT_PREFIX}.*\bCodex P\d+\b"),
        explanation="Codex review marker in comment (session metadata, not code documentation).",
    ),
    Rule(
        name="audit-chunk",
        pattern=re.compile(rf"{COMMENT_PREFIX}.*\baudit chunk \d+\b", re.IGNORECASE),
        explanation="Audit chunk reference in comment (session metadata).",
    ),
    Rule(
        name="audit-item",
        pattern=re.compile(rf"{COMMENT_PREFIX}.*\baudit\b.*item #\d+", re.IGNORECASE),
        explanation="Audit item number in comment (session metadata).",
    ),
    Rule(
        name="dated-action",
        # "Removed 2026-05-17", "Added 2026-05-17", "Changed 2026-05-17"
        pattern=re.compile(
            rf"{COMMENT_PREFIX}.*\b(Removed|Added|Changed|Updated|Migrated|Replaced|Modified)\b "
            r"\d{4}-\d{2}-\d{2}",
        ),
        explanation="Dated action verb in comment (Style D: git log already has this).",
    ),
    Rule(
        name="dated-verified",
        pattern=re.compile(rf"{COMMENT_PREFIX}.*\bVerified\b \d{{4}}-\d{{2}}-\d{{2}}"),
        explanation="Dated empirical-verification stamp (Style D: institutional memory belongs in commit message).",
    ),
    Rule(
        name="previously-did",
        # narrative drift: "previously did X but now Y"
        pattern=re.compile(
            rf"{COMMENT_PREFIX}.*\b(previously|formerly|used to)\b.*\b(but now|now)\b",
            re.IGNORECASE,
        ),
        explanation="Narrative 'previously did X but now Y' (Style D: git log carries this).",
    ),
    Rule(
        name="2.2.x-dated",
        # "since 2.2.13", "in 2.2.14", "removed in 2.2.15", etc.
        # Common pattern of dating internals to a launcher version.
        pattern=re.compile(
            rf"{COMMENT_PREFIX}.*\b(since|in|after|before|removed in|added in|migrated in) "
            r"2\.\d+\.\d+\b",
            re.IGNORECASE,
        ),
        explanation="Version-tied historical reference (Style D: commit message + tag carry this).",
    ),
]


@dataclass
class Hit:
    path: Path
    line_no: int
    line: str
    rule: Rule


def is_license_or_generated(line: str) -> bool:
    # Tolerate dated lines inside SPDX / copyright headers.
    lower = line.lower()
    return any(token in lower for token in ("copyright", "spdx-", "licensed under", "build-time", "generated by"))


def scan_file(path: Path) -> list[Hit]:
    hits: list[Hit] = []
    try:
        with path.open("r", encoding="utf-8", errors="replace") as fh:
            for line_no, line in enumerate(fh, start=1):
                if is_license_or_generated(line):
                    continue
                for rule in RULES:
                    if rule.pattern.search(line):
                        hits.append(Hit(path=path, line_no=line_no, line=line.rstrip(), rule=rule))
                        break  # one hit per line is enough; avoid noise
    except OSError as e:
        print(f"warn: cannot read {path}: {e}", file=sys.stderr)
    return hits


def walk_targets() -> list[Path]:
    out: list[Path] = []
    for d in SCAN_DIRS:
        root = ROOT / d
        if not root.is_dir():
            continue
        for p in root.rglob("*"):
            if p.suffix not in SCAN_EXTS:
                continue
            s = str(p)
            if any(frag in s for frag in EXCLUDE_PATH_FRAGMENTS):
                continue
            out.append(p)
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description="Style-D comment anti-pattern lint.")
    parser.add_argument(
        "--strict",
        action="store_true",
        help="exit 1 if any hits found (default: warn-only, exit 0).",
    )
    parser.add_argument(
        "paths",
        nargs="*",
        type=Path,
        help="restrict scan to these paths (default: all source modules).",
    )
    args = parser.parse_args()

    targets: list[Path] = []
    if args.paths:
        for p in args.paths:
            p = p if p.is_absolute() else (Path.cwd() / p).resolve()
            if p.is_file() and p.suffix in SCAN_EXTS:
                targets.append(p)
            elif p.is_dir():
                for sub in p.rglob("*"):
                    if sub.suffix in SCAN_EXTS and not any(frag in str(sub) for frag in EXCLUDE_PATH_FRAGMENTS):
                        targets.append(sub)
    else:
        targets = walk_targets()

    all_hits: list[Hit] = []
    for path in targets:
        all_hits.extend(scan_file(path))

    if not all_hits:
        print(f"check-comments: 0 anti-pattern hits across {len(targets)} files.")
        return 0

    by_rule: dict[str, list[Hit]] = {}
    for hit in all_hits:
        by_rule.setdefault(hit.rule.name, []).append(hit)

    print(f"check-comments: {len(all_hits)} anti-pattern hits across {len(targets)} files.")
    print()
    for rule_name in sorted(by_rule.keys()):
        hits = by_rule[rule_name]
        print(f"[{rule_name}] {hits[0].rule.explanation}")
        for hit in hits:
            rel = hit.path.relative_to(ROOT)
            print(f"  {rel}:{hit.line_no}: {hit.line.strip()[:120]}")
        print()

    return 1 if args.strict else 0


if __name__ == "__main__":
    sys.exit(main())
