package hivens.launcher.diag

import hivens.config.Branding
import hivens.core.diag.ActionRing
import hivens.core.logging.Redactor
import hivens.launcher.platform.PlatformPaths
import org.slf4j.LoggerFactory
import java.nio.file.Files
import java.nio.file.Path
import java.time.Instant
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/**
 * Beacon: gather every artefact a support-channel reader needs into one ZIP
 * so a user can attach a single file instead of hunting for crash reports,
 * log files, and system info separately.
 *
 * Bundle layout:
 * ```
 * aura-diagnostic-<sessionId>-<timestamp>.zip
 *   ├── system-info.txt    OS/JVM/RAM/CPU/heap/property snapshot
 *   ├── action-ring.txt    last N ActionRing entries with timestamps
 *   ├── logs/
 *   │   ├── launcher.log         (active rolling file)
 *   │   ├── network.log
 *   │   ├── game.log
 *   │   └── crash.log
 *   └── crash-reports/
 *       └── crash-*.txt    (everything currently in the crash-reports dir)
 * ```
 *
 * All log file contents are routed through [Redactor] one more time at
 * bundle-time. The Pulse pipeline already redacts on write, but this is
 * a defense-in-depth pass: if a future code path ever logs raw without
 * going through `%rmsg`, the bundle still ships a redacted copy. Cheap;
 * Redactor is a few regex replaces over text we're streaming anyway.
 */
object DiagnosticBundle {

    private val log = LoggerFactory.getLogger(DiagnosticBundle::class.java)
    private val tsFmt = DateTimeFormatter.ofPattern("yyyy-MM-dd_HH-mm-ss").withZone(ZoneId.systemDefault())
    private val isoFmt = DateTimeFormatter.ISO_INSTANT

    /** Filenames inside the bundle ZIP that get the Redactor pass on copy-in. */
    private val LOG_FILES = listOf("launcher.log", "network.log", "game.log", "crash.log")

    /**
     * Builds the bundle ZIP under [paths]'s data directory and returns its path.
     * Caller is responsible for deciding what to do with it (open file manager,
     * upload, etc.).
     */
    fun create(paths: PlatformPaths): Path {
        val sessionId = System.getProperty("aura.sessionId", "unknown")
        val timestamp = tsFmt.format(Instant.now())
        val output = paths.dataDir.resolve("aura-diagnostic-$sessionId-$timestamp.zip")

        Files.createDirectories(paths.dataDir)

        ZipOutputStream(Files.newOutputStream(output)).use { zip ->
            writeText(zip, "system-info.txt", buildSystemInfo(paths))
            writeText(zip, "action-ring.txt", buildActionRing())

            // Live log files. Each file is isolated: a single broken file
            // (locked, malformed UTF-8, permission denied) MUST NOT abort the
            // whole bundle -- the bundle is the user's last resort for support
            // and a half-bundle with one missing log is vastly better than
            // none at all. Failures are recorded as a placeholder entry in
            // the ZIP so the support reader knows what was missing and why.
            val logsDir = paths.logsDir
            if (Files.exists(logsDir)) {
                LOG_FILES.forEach { name ->
                    val src = logsDir.resolve(name)
                    if (Files.exists(src)) {
                        copyTextRedacted(zip, "logs/$name", src)
                    }
                }
            }

            // Crash reports -- also routed through Redactor before zipping, even
            // though they were generated by CrashReporter (which doesn't write
            // secrets itself). The reason is `throwable.stackTraceToString()`:
            // exception messages can echo URL params from a failed request,
            // including accessToken values. Since the bundle is explicitly
            // intended for sharing with maintainers, defense-in-depth here
            // prevents a sneaky leak path that the Pulse `%rmsg` / `%rex`
            // pipeline would have caught only for newly-logged events.
            val crashDir = paths.crashDir
            if (Files.exists(crashDir)) {
                Files.list(crashDir).use { stream ->
                    // NOFOLLOW_LINKS so a symlink dropped into crash-reports/
                    // (deliberately or by tooling) doesn't leak its target's
                    // contents into a bundle that's about to be sent to
                    // maintainers. Same family as #187 ZIP/TAR hardening.
                    stream.filter { Files.isRegularFile(it, java.nio.file.LinkOption.NOFOLLOW_LINKS) }.forEach { f ->
                        copyTextRedacted(zip, "crash-reports/${f.fileName}", f)
                    }
                }
            }
        }

        log.info("Diagnostic bundle written: {}", output.toAbsolutePath())
        return output
    }

    private fun buildSystemInfo(paths: PlatformPaths): String = buildString {
        val rt = Runtime.getRuntime()
        appendLine("==============================")
        appendLine(" Aura Launcher diagnostic bundle")
        appendLine("==============================")
        appendLine(" Generated  : ${isoFmt.format(Instant.now())}")
        appendLine(" Version    : ${Branding.VERSION}")
        appendLine(" SessionId  : ${System.getProperty("aura.sessionId", "unknown")}")
        appendLine()
        appendLine(" OS         : ${System.getProperty("os.name")} ${System.getProperty("os.version")} (${System.getProperty("os.arch")})")
        appendLine(" JVM        : ${System.getProperty("java.version")} (${System.getProperty("java.vendor")})")
        appendLine(" JVM home   : ${System.getProperty("java.home")}")
        appendLine(" Locale     : ${java.util.Locale.getDefault()}")
        appendLine(" Timezone   : ${java.util.TimeZone.getDefault().id}")
        appendLine()
        appendLine(" CPU cores  : ${rt.availableProcessors()}")
        appendLine(" Max heap   : ${rt.maxMemory() / 1_000_000} MB")
        appendLine(" Total heap : ${rt.totalMemory() / 1_000_000} MB")
        appendLine(" Free heap  : ${rt.freeMemory() / 1_000_000} MB")
        appendLine()
        appendLine(" user.home  : ${System.getProperty("user.home")}")
        appendLine(" user.dir   : ${System.getProperty("user.dir")}")
        // Path-based, not string-slicing: prior version did
        // `aura.logs.dir.substringBeforeLast("/logs", "(unknown)")` which fell
        // back to "(unknown)" on Windows because the path separator is `\`,
        // dropping a support-critical signal exactly for Windows users.
        appendLine(" data.dir   : ${paths.dataDir.toAbsolutePath()}")
        appendLine(" logs.dir   : ${paths.logsDir.toAbsolutePath()}")
    }

    private fun buildActionRing(): String = buildString {
        val entries = ActionRing.snapshot()
        appendLine("Action ring (oldest first, last ${ActionRing.CAPACITY} entries):")
        if (entries.isEmpty()) {
            appendLine("  (no actions recorded yet)")
        } else {
            val fmt = DateTimeFormatter.ofPattern("HH:mm:ss.SSS").withZone(ZoneId.systemDefault())
            entries.forEach { e ->
                appendLine("  [${fmt.format(e.timestamp)}] ${e.text}")
            }
        }
    }

    private fun writeText(zip: ZipOutputStream, entryName: String, content: String) {
        zip.putNextEntry(ZipEntry(entryName))
        zip.write(content.toByteArray(Charsets.UTF_8))
        zip.closeEntry()
    }

    /**
     * Copy [src] into the ZIP under [entryName], routing the contents through
     * [Redactor] first. If reading [src] throws (locked file, permission denied,
     * malformed UTF-8), write a placeholder entry instead of aborting the whole
     * bundle. The bundle is the user's support last resort -- partial is much
     * better than nothing.
     */
    private fun copyTextRedacted(zip: ZipOutputStream, entryName: String, src: Path) {
        val payload = runCatching { Redactor.redact(Files.readString(src)) }
            .getOrElse { e ->
                log.warn("Diagnostic bundle: skipping unreadable {} ({}): {}",
                    src, e.javaClass.simpleName, e.message)
                "<unreadable: ${e.javaClass.simpleName}: ${e.message}>"
            }
        writeText(zip, entryName, payload)
    }
}
