package hivens.launcher.diag

import hivens.config.Branding
import hivens.core.diag.ActionRing
import hivens.core.logging.Redactor
import hivens.launcher.platform.PlatformPaths
import org.slf4j.LoggerFactory
import java.nio.file.Files
import java.nio.file.Path
import java.time.Instant
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/**
 * Beacon: gather every artefact a support-channel reader needs into one ZIP
 * so a user can attach a single file instead of hunting for crash reports,
 * log files, and system info separately.
 *
 * Bundle layout:
 * ```
 * aura-diagnostic-<sessionId>-<timestamp>.zip
 *   ├── system-info.txt    OS/JVM/RAM/CPU/heap/property snapshot
 *   ├── action-ring.txt    last N ActionRing entries with timestamps
 *   ├── logs/
 *   │   ├── launcher.log         (active rolling file)
 *   │   ├── network.log
 *   │   ├── game.log
 *   │   └── crash.log
 *   └── crash-reports/
 *       └── crash-*.txt    (everything currently in the crash-reports dir)
 * ```
 *
 * All log file contents are routed through [Redactor] one more time at
 * bundle-time. The Pulse pipeline already redacts on write, but this is
 * a defence-in-depth pass: if a future code path ever logs raw without
 * going through `%rmsg`, the bundle still ships a redacted copy. Cheap;
 * Redactor is a few regex replaces over text we're streaming anyway.
 */
object DiagnosticBundle {

    private val log = LoggerFactory.getLogger(DiagnosticBundle::class.java)
    private val tsFmt = DateTimeFormatter.ofPattern("yyyy-MM-dd_HH-mm-ss").withZone(ZoneId.systemDefault())
    private val isoFmt = DateTimeFormatter.ISO_INSTANT

    /** Filenames inside the bundle ZIP that get the Redactor pass on copy-in. */
    private val LOG_FILES = listOf("launcher.log", "network.log", "game.log", "crash.log")

    /**
     * Builds the bundle ZIP under [paths]'s data directory and returns its path.
     * Caller is responsible for deciding what to do with it (open file manager,
     * upload, etc.).
     */
    fun create(paths: PlatformPaths): Path {
        val sessionId = System.getProperty("aura.sessionId", "unknown")
        val timestamp = tsFmt.format(Instant.now())
        val output = paths.dataDir.resolve("aura-diagnostic-$sessionId-$timestamp.zip")

        Files.createDirectories(paths.dataDir)

        ZipOutputStream(Files.newOutputStream(output)).use { zip ->
            writeText(zip, "system-info.txt", buildSystemInfo())
            writeText(zip, "action-ring.txt", buildActionRing())

            // Live log files
            val logsDir = paths.logsDir
            if (Files.exists(logsDir)) {
                LOG_FILES.forEach { name ->
                    val src = logsDir.resolve(name)
                    if (Files.exists(src)) {
                        writeText(zip, "logs/$name", Redactor.redact(Files.readString(src)))
                    }
                }
            }

            // Crash reports — also routed through Redactor before zipping, even
            // though they were generated by CrashReporter (which doesn't write
            // secrets itself). The reason is `throwable.stackTraceToString()`:
            // exception messages can echo URL params from a failed request,
            // including accessToken values. Since the bundle is explicitly
            // intended for sharing with maintainers, defence-in-depth here
            // prevents a sneaky leak path that the Pulse `%rmsg` / `%rex`
            // pipeline would have caught only for newly-logged events.
            val crashDir = paths.crashDir
            if (Files.exists(crashDir)) {
                Files.list(crashDir).use { stream ->
                    stream.filter { Files.isRegularFile(it) }.forEach { f ->
                        writeText(zip, "crash-reports/${f.fileName}", Redactor.redact(Files.readString(f)))
                    }
                }
            }
        }

        log.info("Diagnostic bundle written: {}", output.toAbsolutePath())
        return output
    }

    private fun buildSystemInfo(): String = buildString {
        val rt = Runtime.getRuntime()
        appendLine("==============================")
        appendLine(" Aura Launcher diagnostic bundle")
        appendLine("==============================")
        appendLine(" Generated  : ${isoFmt.format(Instant.now())}")
        appendLine(" Version    : ${Branding.VERSION}")
        appendLine(" SessionId  : ${System.getProperty("aura.sessionId", "unknown")}")
        appendLine()
        appendLine(" OS         : ${System.getProperty("os.name")} ${System.getProperty("os.version")} (${System.getProperty("os.arch")})")
        appendLine(" JVM        : ${System.getProperty("java.version")} (${System.getProperty("java.vendor")})")
        appendLine(" JVM home   : ${System.getProperty("java.home")}")
        appendLine(" Locale     : ${java.util.Locale.getDefault()}")
        appendLine(" Timezone   : ${java.util.TimeZone.getDefault().id}")
        appendLine()
        appendLine(" CPU cores  : ${rt.availableProcessors()}")
        appendLine(" Max heap   : ${rt.maxMemory() / 1_000_000} MB")
        appendLine(" Total heap : ${rt.totalMemory() / 1_000_000} MB")
        appendLine(" Free heap  : ${rt.freeMemory() / 1_000_000} MB")
        appendLine()
        appendLine(" user.home  : ${System.getProperty("user.home")}")
        appendLine(" user.dir   : ${System.getProperty("user.dir")}")
        appendLine(" data.dir   : ${System.getProperty("aura.logs.dir", "(unset)").substringBeforeLast("/logs", "(unknown)")}")
    }

    private fun buildActionRing(): String = buildString {
        val entries = ActionRing.snapshot()
        appendLine("Action ring (oldest first, last ${ActionRing.CAPACITY} entries):")
        if (entries.isEmpty()) {
            appendLine("  (no actions recorded yet)")
        } else {
            val fmt = DateTimeFormatter.ofPattern("HH:mm:ss.SSS").withZone(ZoneId.systemDefault())
            entries.forEach { e ->
                appendLine("  [${fmt.format(e.timestamp)}] ${e.text}")
            }
        }
    }

    private fun writeText(zip: ZipOutputStream, entryName: String, content: String) {
        zip.putNextEntry(ZipEntry(entryName))
        zip.write(content.toByteArray(Charsets.UTF_8))
        zip.closeEntry()
    }
}
