package hivens.launcher.diag

import hivens.config.Branding
import hivens.core.diag.ActionRing
import hivens.core.logging.Redactor
import hivens.launcher.platform.PlatformPaths
import org.slf4j.LoggerFactory
import java.nio.file.Files
import java.nio.file.Path
import java.time.Instant
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/**
 * Beacon: gather every artefact a support-channel reader needs into one ZIP
 * so a user can attach a single file instead of hunting for crash reports,
 * log files, and system info separately.
 *
 * Bundle layout:
 * ```
 * nexira-diagnostic-<sessionId>-<timestamp>.zip
 *   ├── system-info.txt    OS/JVM/RAM/CPU/heap/property snapshot
 *   ├── action-ring.txt    last N ActionRing entries with timestamps
 *   ├── logs/
 *   │   ├── launcher.log         (active rolling file)
 *   │   ├── network.log
 *   │   ├── game.log
 *   │   └── crash.log
 *   └── crash-reports/
 *       └── crash-*.txt    (everything currently in the crash-reports dir)
 * ```
 *
 * All log file contents are routed through [Redactor] one more time at
 * bundle-time. The Pulse pipeline already redacts on write, but this is
 * a defense-in-depth pass: if a future code path ever logs raw without
 * going through `%rmsg`, the bundle still ships a redacted copy. Cheap;
 * Redactor is a few regex replaces over text we're streaming anyway.
 */
object DiagnosticBundle {

    private val log = LoggerFactory.getLogger(DiagnosticBundle::class.java)
    private val tsFmt = DateTimeFormatter.ofPattern("yyyy-MM-dd_HH-mm-ss").withZone(ZoneId.systemDefault())
    private val isoFmt = DateTimeFormatter.ISO_INSTANT

    /** Filenames inside the bundle ZIP that get the Redactor pass on copy-in. */
    private val LOG_FILES = listOf("launcher.log", "network.log", "game.log", "crash.log")

    /**
     * Builds the bundle ZIP under [paths]'s data directory and returns its path.
     * Caller is responsible for deciding what to do with it (open file manager,
     * upload, etc.).
     */
    fun create(paths: PlatformPaths, disabledModules: Set<String> = emptySet()): Path {
        val sessionId = System.getProperty("nexira.sessionId", "unknown")
        val timestamp = tsFmt.format(Instant.now())
        val output = paths.dataDir.resolve("nexira-diagnostic-$sessionId-$timestamp.zip")

        Files.createDirectories(paths.dataDir)

        ZipOutputStream(Files.newOutputStream(output)).use { zip ->
            // Both go through Redactor like the log files do. The bundle is
            // offered to the user as redacted, and these two were the entries
            // that were not: an action-ring line quotes whatever a call site
            // recorded, and a path line carries the account name the OS put in
            // it.
            writeText(zip, "system-info.txt", Redactor.redact(buildSystemInfo(paths, disabledModules)))
            writeText(zip, "action-ring.txt", Redactor.redact(buildActionRing()))

            // Live log files. Each file is isolated: a single broken file
            // (locked, malformed UTF-8, permission denied) MUST NOT abort the
            // whole bundle -- the bundle is the user's last resort for support
            // and a half-bundle with one missing log is vastly better than
            // none at all. Failures are recorded as a placeholder entry in
            // the ZIP so the support reader knows what was missing and why.
            val logsDir = paths.logsDir
            if (Files.exists(logsDir)) {
                LOG_FILES.forEach { name ->
                    val src = logsDir.resolve(name)
                    if (Files.exists(src)) {
                        copyTextRedacted(zip, "logs/$name", src)
                    }
                }
            }

            // Crash reports -- also routed through Redactor before zipping, even
            // though they were generated by CrashReporter (which doesn't write
            // secrets itself). The reason is `throwable.stackTraceToString()`:
            // exception messages can echo URL params from a failed request,
            // including accessToken values. Since the bundle is explicitly
            // intended for sharing with maintainers, defense-in-depth here
            // prevents a sneaky leak path that the Pulse `%rmsg` / `%rex`
            // pipeline would have caught only for newly-logged events.
            val crashDir = paths.crashDir
            if (Files.exists(crashDir)) {
                Files.list(crashDir).use { stream ->
                    // NOFOLLOW_LINKS so a symlink dropped into
                    // crash-reports/ (deliberately or by tooling)
                    // doesn't leak its target's contents into a
                    // bundle that's about to be sent to maintainers.
                    stream.filter { Files.isRegularFile(it, java.nio.file.LinkOption.NOFOLLOW_LINKS) }.forEach { f ->
                        copyTextRedacted(zip, "crash-reports/${f.fileName}", f)
                    }
                }
            }
        }

        log.info("Diagnostic bundle written: {}", output.toAbsolutePath())
        return output
    }

    private fun buildSystemInfo(paths: PlatformPaths, disabledModules: Set<String>): String = buildString {
        val rt = Runtime.getRuntime()
        appendLine("==============================")
        appendLine(" Nexira diagnostic bundle")
        appendLine("==============================")
        appendLine(" Generated  : ${isoFmt.format(Instant.now())}")
        appendLine(" Version    : ${Branding.VERSION}")
        appendLine(" SessionId  : ${System.getProperty("nexira.sessionId", "unknown")}")
        // A module switched off by boot recovery stays off across restarts and
        // changes what whole features do -- with skinema off, every player
        // reports that it cannot open the file. Nothing else in the bundle says
        // which ones are off, so a report reads as a broken feature rather than
        // a disabled one.
        appendLine(" Modules off: ${disabledModules.sorted().joinToString(", ").ifEmpty { "(none)" }}")
        appendLine()
        appendLine(" OS         : ${System.getProperty("os.name")} ${System.getProperty("os.version")} (${System.getProperty("os.arch")})")
        appendLine(" JVM        : ${System.getProperty("java.version")} (${System.getProperty("java.vendor")})")
        // Folded too: a Gradle- or SDKMAN-provisioned JDK lives under the home
        // directory, so this line carried the account name as readily as the
        // four below it.
        appendLine(" JVM home   : ${abbreviateHome(System.getProperty("java.home") ?: "")}")
        appendLine(" Locale     : ${java.util.Locale.getDefault()}")
        appendLine(" Timezone   : ${java.util.TimeZone.getDefault().id}")
        appendLine()
        appendLine(" CPU cores  : ${rt.availableProcessors()}")
        appendLine(" Max heap   : ${rt.maxMemory() / 1_000_000} MB")
        appendLine(" Total heap : ${rt.totalMemory() / 1_000_000} MB")
        appendLine(" Free heap  : ${rt.freeMemory() / 1_000_000} MB")
        appendLine()
        // Paths with the home prefix folded back to `~`. Support needs the
        // shape of the layout -- which drive, whether the data dir was moved,
        // how deep it sits -- and none of that needs the account name the OS
        // baked into every one of these four lines.
        appendLine(" user.home  : ${abbreviateHome(System.getProperty("user.home"))}")
        appendLine(" user.dir   : ${abbreviateHome(System.getProperty("user.dir"))}")
        appendLine(" data.dir   : ${abbreviateHome(paths.dataDir.toAbsolutePath().toString())}")
        appendLine(" logs.dir   : ${abbreviateHome(paths.logsDir.toAbsolutePath().toString())}")
    }

    /**
     * `/home/alice/.local/share/nexira` -> `~/.local/share/nexira`. The home
     * directory itself becomes a bare `~`. Returns [path] unchanged when it
     * does not sit under the home directory, since an absolute path elsewhere
     * (a second drive, a moved data dir) carries no account name to begin with.
     */
    internal fun abbreviateHome(path: String, home: String = System.getProperty("user.home") ?: ""): String {
        if (home.isBlank()) return path
        val normalisedHome = home.trimEnd('/', '\\')
        return when {
            path == normalisedHome -> "~"
            path.startsWith(normalisedHome + "/") || path.startsWith(normalisedHome + "\\") ->
                "~" + path.substring(normalisedHome.length)
            else -> path
        }
    }

    private fun buildActionRing(): String = buildString {
        val entries = ActionRing.snapshot()
        appendLine("Action ring (oldest first, last ${ActionRing.CAPACITY} entries):")
        if (entries.isEmpty()) {
            appendLine("  (no actions recorded yet)")
        } else {
            val fmt = DateTimeFormatter.ofPattern("HH:mm:ss.SSS").withZone(ZoneId.systemDefault())
            entries.forEach { e ->
                appendLine("  [${fmt.format(e.timestamp)}] ${e.text}")
            }
        }
    }

    private fun writeText(zip: ZipOutputStream, entryName: String, content: String) {
        zip.putNextEntry(ZipEntry(entryName))
        zip.write(content.toByteArray(Charsets.UTF_8))
        zip.closeEntry()
    }

    /**
     * Copy [src] into the ZIP under [entryName], routing the contents through
     * [Redactor] first. If reading [src] throws (locked file, permission denied,
     * malformed UTF-8), write a placeholder entry instead of aborting the whole
     * bundle. The bundle is the user's support last resort -- partial is much
     * better than nothing.
     */
    private fun copyTextRedacted(zip: ZipOutputStream, entryName: String, src: Path) {
        val payload = runCatching { Redactor.redact(Files.readString(src)) }
            .getOrElse { e ->
                log.warn("Diagnostic bundle: skipping unreadable {} ({}): {}",
                    src, e.javaClass.simpleName, e.message)
                "<unreadable: ${e.javaClass.simpleName}: ${e.message}>"
            }
        writeText(zip, entryName, payload)
    }
}
