package hivens.launcher.diag

import hivens.config.Branding
import hivens.core.diag.ActionRing
import hivens.core.logging.Redactor
import hivens.launcher.CrashReporter
import java.net.URLEncoder
import java.nio.file.Path
import java.time.ZoneId
import java.time.format.DateTimeFormatter

/**
 * Builds pre-filled GitHub `/issues/new?title=&body=&labels=` URLs for the two
 * Beacon entry points: crash dialog and diagnostic bundle dialog. Opening one
 * of these URLs takes the user to a GitHub Issue editor with everything we
 * could autofill already in place — they review, edit, submit. Nothing leaves
 * the machine until the user clicks the GitHub "Submit" button on github.com.
 *
 * This is the principled alternative to telemetry (see [[user_privacy_stance]]):
 * convenience for both sides without a phone-home codepath in the binary. The
 * launcher never POSTs anything; the browser does, with the user reviewing.
 *
 * URL length budget: ~8 KB is the practical cap before browsers (Chrome/Firefox)
 * start truncating GET URLs. We aim for ≤ 6500 chars total so title + body URL-
 * encoded fit comfortably with the [Branding.ISSUE_NEW_URL] prefix and labels.
 */
object IssueReporter {

    private const val MAX_BODY_LEN_RAW = 6000
    private const val ACTION_RING_LIMIT = 20
    private const val STACK_TRACE_LIMIT = 3000

    private val entryTimeFmt = DateTimeFormatter.ofPattern("HH:mm:ss.SSS")
        .withZone(ZoneId.systemDefault())

    /** URL that opens a new Issue pre-filled with the crash report. */
    fun crashIssueUrl(report: CrashReporter.CrashReport): String {
        // Title also goes through Redactor: it ends up in the GET URL, which
        // means browser history / corporate proxy logs / GitHub request logs
        // would all see it raw. Body redaction alone isn't enough.
        val rawTitle = "[crash] ${report.thread}: ${report.stackTrace.lineSequence().firstOrNull().orEmpty().take(120)}"
        val title = Redactor.redact(rawTitle)
        val body = buildCrashBody(report)
        return buildUrl(title = title, body = body, labels = "crash,auto-report")
    }

    /** URL that opens a new Issue with instructions to attach the bundle ZIP. */
    fun bundleIssueUrl(bundlePath: Path): String {
        val title = "[bug] "
        val body = buildBundleBody(bundlePath)
        return buildUrl(title = title, body = body, labels = "bug,with-bundle")
    }

    // ── Body templates ──────────────────────────────────────────────────────

    private fun buildCrashBody(report: CrashReporter.CrashReport): String {
        val ring = ActionRing.snapshot().takeLast(ACTION_RING_LIMIT)
        val ringBlock = if (ring.isEmpty()) "_(no actions recorded)_"
        else ring.joinToString("\n") { e ->
            "- `[${entryTimeFmt.format(e.timestamp)}]` ${e.text}"
        }
        val truncatedStack = report.stackTrace.take(STACK_TRACE_LIMIT) +
            if (report.stackTrace.length > STACK_TRACE_LIMIT) "\n... (truncated; full trace in crash file)" else ""

        // All free-form fields routed through Redactor — defence in depth.
        // CrashReporter doesn't generate report.lastAction-style sensitive fields
        // anymore, but stack traces can include URL params with tokens.
        return Redactor.redact(buildString {
            appendLine("## Описание")
            appendLine("<!-- Опишите что вы делали когда лаунчер упал. -->")
            appendLine()
            appendLine("## Crash report")
            appendLine()
            appendLine("- **Version:** ${report.version}")
            appendLine("- **OS:** ${report.osName} ${report.osVersion} (${report.osArch})")
            appendLine("- **JVM:** ${report.jvmVersion} (${report.jvmVendor})")
            appendLine("- **Max heap:** ${report.maxMemoryMb} MB")
            appendLine("- **Thread:** `${report.thread}`")
            appendLine("- **Generated:** ${report.timestamp}")
            appendLine()
            appendLine("## Recent actions")
            appendLine(ringBlock)
            appendLine()
            appendLine("## Stack trace")
            appendLine("```")
            appendLine(truncatedStack)
            appendLine("```")
            appendLine()
            appendLine("---")
            appendLine("_Auto-generated by Aura Launcher Beacon. Edit before submitting if needed._")
        }).take(MAX_BODY_LEN_RAW)
    }

    private fun buildBundleBody(bundlePath: Path): String = buildString {
        appendLine("## Описание")
        appendLine("<!-- Опишите проблему. -->")
        appendLine()
        appendLine("## Diagnostic bundle")
        appendLine()
        appendLine("Diagnostic bundle ZIP сгенерирован и его путь скопирован в буфер обмена:")
        appendLine()
        appendLine("```")
        appendLine(bundlePath.toAbsolutePath().toString())
        appendLine("```")
        appendLine()
        appendLine("**Перетащите этот ZIP в это окно перед отправкой Issue** (GitHub поддерживает drag-and-drop).")
        appendLine("Содержимое: redacted launcher / network / game / crash logs, action ring, system info, crash reports.")
        appendLine()
        appendLine("---")
        appendLine("- **Aura Launcher version:** ${Branding.VERSION}")
        appendLine("- **OS:** ${System.getProperty("os.name")} ${System.getProperty("os.version")} (${System.getProperty("os.arch")})")
    }.take(MAX_BODY_LEN_RAW)

    // ── URL assembly ────────────────────────────────────────────────────────

    private fun buildUrl(title: String, body: String, labels: String): String {
        val titleEnc  = URLEncoder.encode(title,  Charsets.UTF_8)
        val bodyEnc   = URLEncoder.encode(body,   Charsets.UTF_8)
        val labelsEnc = URLEncoder.encode(labels, Charsets.UTF_8)
        return "${Branding.ISSUE_NEW_URL}?title=$titleEnc&body=$bodyEnc&labels=$labelsEnc"
    }
}
