package hivens.widget.processor

/**
 * One widget as the registry needs it, with every KSP type left behind. The
 * processor resolves symbols into these; everything downstream (collision
 * detection, source rendering) is a pure function of the list, which is the
 * half worth testing -- a wrong registry compiles fine and shows up only as a
 * widget that silently fails to draw.
 */
internal data class WidgetModel(
    val id: String,
    val displayName: String,
    val removable: Boolean,
    val slots: List<String>,
    /** FQN of the @Serializable props class, or null for a propless widget. */
    val propsClassFqn: String?,
    val functionFqn: String,
    /** Service contracts from @ProvidesService, by FQN. */
    val provides: List<String> = emptyList(),
    /** Service contracts from @InjectService, by FQN. */
    val injects: List<String> = emptyList(),
)

/**
 * Injected contracts no widget in this build provides, keyed by the widget that
 * reads them.
 *
 * A consumer whose provider is absent is not a crash: the registry hands it
 * null every frame and the widget renders its disabled state forever. That is
 * correct behaviour for a provider the user has not placed yet, and
 * indistinguishable from a contract nothing can ever satisfy -- which is what
 * this separates.
 */
internal fun injectorsWithoutProvider(widgets: List<WidgetModel>): Map<WidgetModel, List<String>> {
    val provided = widgets.flatMapTo(HashSet()) { it.provides }
    return widgets
        .associateWith { widget -> widget.injects.filterNot { it in provided } }
        .filterValues { it.isNotEmpty() }
}

internal const val GENERATED_PACKAGE = "hivens.widget.generated"
internal const val GENERATED_FILE_NAME = "GeneratedWidgetRegistry"

/**
 * Ids declared more than once, keyed by id. The generated registry is a
 * `buildMap { put(...) }` and buildMap keeps the LAST put per key, so a shared
 * id would drop a widget with no diagnostic at all. The processor turns a
 * non-empty result into build errors instead.
 */
internal fun duplicateIds(widgets: List<WidgetModel>): Map<String, List<WidgetModel>> =
    widgets.groupBy { it.id }.filterValues { it.size > 1 }

/** Renders the registry object. Deterministic in the order of [widgets]. */
internal fun renderRegistry(widgets: List<WidgetModel>): String = buildString {
    appendLine("// Generated by hivens.widget.processor.WidgetRegistryProcessor.")
    appendLine("// Do not edit -- changes are overwritten on the next build.")
    appendLine("package $GENERATED_PACKAGE")
    appendLine()
    appendLine("import androidx.compose.runtime.Composable")
    appendLine("import hivens.widget.api.WidgetDescriptor")
    appendLine("import hivens.widget.api.WidgetRegistry")
    appendLine("import hivens.widget.model.SlotId")
    appendLine("import hivens.widget.model.WidgetInstance")
    appendLine("import hivens.widget.model.WidgetKind")
    // Serialization imports + the shared Json only when at least one widget
    // declares props -- otherwise they would be unused and warn on a
    // props-free build.
    val hasProps = widgets.any { it.propsClassFqn != null }
    if (hasProps) {
        appendLine("import kotlinx.serialization.KSerializer")
        appendLine("import kotlinx.serialization.json.Json")
        appendLine("import kotlinx.serialization.json.JsonObject")
        appendLine("import kotlinx.serialization.json.jsonObject")
    }
    appendLine()
    appendLine("object $GENERATED_FILE_NAME : WidgetRegistry {")
    if (hasProps) {
        // encodeDefaults so the default-props baseline carries every field;
        // the editor overlays the instance's stored overrides.
        appendLine("    private val propsJson: Json = Json { encodeDefaults = true; ignoreUnknownKeys = true }")
    }
    appendLine("    private val map: Map<WidgetKind, WidgetDescriptor> = buildMap {")
    widgets.forEach { entry ->
        val kindLiteral = "WidgetKind(\"${entry.id.kotlinEscape()}\")"
        appendLine("        put($kindLiteral, object : WidgetDescriptor {")
        appendLine("            override val kind: WidgetKind = $kindLiteral")
        appendLine("            override val displayName: String = \"${entry.displayName.kotlinEscape()}\"")
        appendLine("            override val removable: Boolean = ${entry.removable}")
        appendLine("            override val slots: List<SlotId> = ${entry.slots.toSlotIdListLiteral()}")
        if (entry.provides.isNotEmpty()) {
            appendLine("            override val provides: Set<String> = ${entry.provides.toStringSetLiteral()}")
        }
        if (entry.injects.isNotEmpty()) {
            appendLine("            override val injects: Set<String> = ${entry.injects.toStringSetLiteral()}")
        }
        if (entry.propsClassFqn != null) {
            val fqn = entry.propsClassFqn
            appendLine("            override val propsSerializer: KSerializer<*>? = $fqn.serializer()")
            appendLine("            override val defaultPropsJson: JsonObject =")
            appendLine("                propsJson.encodeToJsonElement($fqn.serializer(), $fqn()).jsonObject")
        }
        appendLine("            @Composable override fun Render(instance: WidgetInstance) {")
        appendLine("                ${entry.functionFqn}(instance)")
        appendLine("            }")
        appendLine("        })")
    }
    appendLine("    }")
    appendLine()
    appendLine("    override fun all(): Map<WidgetKind, WidgetDescriptor> = map")
    appendLine("    override fun get(kind: WidgetKind): WidgetDescriptor? = map[kind]")
    appendLine("}")
}

private fun List<String>.toStringSetLiteral(): String =
    joinToString(prefix = "setOf(", postfix = ")") { "\"${it.kotlinEscape()}\"" }

private fun List<String>.toSlotIdListLiteral(): String =
    if (isEmpty()) "emptyList()"
    else joinToString(prefix = "listOf(", postfix = ")") { "SlotId(\"${it.kotlinEscape()}\")" }

private fun String.kotlinEscape(): String =
    replace("\\", "\\\\").replace("\"", "\\\"")
