package hivens.widget.processor

import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSFunctionDeclaration

private const val WIDGET_ANNOTATION_FQN = "hivens.widget.model.Widget"

private const val GENERATED_PACKAGE = "hivens.widget.generated"
private const val GENERATED_FILE_NAME = "GeneratedWidgetRegistry"

class WidgetRegistryProcessor(
    private val env: SymbolProcessorEnvironment,
) : SymbolProcessor {

    // KSP multi-round contract: process() can be called more than once
    // until no new symbols are deferred. We collect all valid widgets
    // across rounds and emit a single file on first round only -- KSP
    // will short-circuit subsequent rounds because nothing was deferred.
    private var emitted = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (emitted) return emptyList()

        val symbols = resolver
            .getSymbolsWithAnnotation(WIDGET_ANNOTATION_FQN)
            .toList()

        val widgets = symbols.mapNotNull { symbol ->
            if (symbol !is KSFunctionDeclaration) {
                env.logger.error("@Widget is only valid on functions", symbol)
                return@mapNotNull null
            }
            val extracted = WidgetValidator.validate(symbol, env) ?: return@mapNotNull null
            val packageName = symbol.packageName.asString()
            val funcName = symbol.simpleName.asString()
            WidgetEntry(
                id = extracted.id,
                displayName = extracted.displayName.ifBlank { funcName },
                removable = extracted.removable,
                slots = extracted.slots,
                propsClassFqn = extracted.propsClassFqn,
                functionFqn = if (packageName.isEmpty()) funcName else "$packageName.$funcName",
                containingFile = symbol.containingFile,
            )
        }

        if (widgets.isEmpty() && symbols.isNotEmpty()) {
            // Some symbols matched but all failed validation; emit nothing
            // so the build fails on diagnostics rather than producing a
            // stub registry that silently drops widgets.
            return emptyList()
        }

        emitGeneratedFile(widgets)
        emitted = true
        return emptyList()
    }

    private fun emitGeneratedFile(widgets: List<WidgetEntry>) {
        val sourceFiles = widgets.mapNotNull { it.containingFile }.toTypedArray()
        // aggregating = true: any change to ANY @Widget source invalidates
        // the generated registry; KSP needs this for correct incremental
        // behavior when widgets are added or renamed.
        val deps = Dependencies(aggregating = true, sources = sourceFiles)
        env.codeGenerator.createNewFile(
            dependencies = deps,
            packageName = GENERATED_PACKAGE,
            fileName = GENERATED_FILE_NAME,
            extensionName = "kt",
        ).use { stream ->
            stream.writer(Charsets.UTF_8).use { writer ->
                writer.write(renderFile(widgets))
            }
        }
    }

    private fun renderFile(widgets: List<WidgetEntry>): String = buildString {
        appendLine("// Generated by hivens.widget.processor.WidgetRegistryProcessor.")
        appendLine("// Do not edit -- changes are overwritten on the next build.")
        appendLine("package $GENERATED_PACKAGE")
        appendLine()
        appendLine("import androidx.compose.runtime.Composable")
        appendLine("import hivens.widget.api.WidgetDescriptor")
        appendLine("import hivens.widget.api.WidgetRegistry")
        appendLine("import hivens.widget.model.SlotId")
        appendLine("import hivens.widget.model.WidgetInstance")
        appendLine("import hivens.widget.model.WidgetKind")
        // Serialization imports + the shared Json only when at least one
        // widget declares props -- otherwise they would be unused and
        // warn on a props-free build.
        val hasProps = widgets.any { it.propsClassFqn != null }
        if (hasProps) {
            appendLine("import kotlinx.serialization.KSerializer")
            appendLine("import kotlinx.serialization.json.Json")
            appendLine("import kotlinx.serialization.json.JsonObject")
            appendLine("import kotlinx.serialization.json.jsonObject")
        }
        appendLine()
        appendLine("object $GENERATED_FILE_NAME : WidgetRegistry {")
        if (hasProps) {
            // encodeDefaults so the default-props baseline carries every
            // field; the editor overlays the instance's stored overrides.
            appendLine("    private val propsJson: Json = Json { encodeDefaults = true; ignoreUnknownKeys = true }")
        }
        appendLine("    private val map: Map<WidgetKind, WidgetDescriptor> = buildMap {")
        widgets.forEach { entry ->
            val kindLiteral = "WidgetKind(\"${entry.id.kotlinEscape()}\")"
            appendLine("        put($kindLiteral, object : WidgetDescriptor {")
            appendLine("            override val kind: WidgetKind = $kindLiteral")
            appendLine("            override val displayName: String = \"${entry.displayName.kotlinEscape()}\"")
            appendLine("            override val removable: Boolean = ${entry.removable}")
            appendLine("            override val slots: List<SlotId> = ${entry.slots.toSlotIdListLiteral()}")
            if (entry.propsClassFqn != null) {
                val fqn = entry.propsClassFqn
                appendLine("            override val propsSerializer: KSerializer<*>? = $fqn.serializer()")
                appendLine("            override val defaultPropsJson: JsonObject =")
                appendLine("                propsJson.encodeToJsonElement($fqn.serializer(), $fqn()).jsonObject")
            }
            appendLine("            @Composable override fun Render(instance: WidgetInstance) {")
            appendLine("                ${entry.functionFqn}(instance)")
            appendLine("            }")
            appendLine("        })")
        }
        appendLine("    }")
        appendLine()
        appendLine("    override fun all(): Map<WidgetKind, WidgetDescriptor> = map")
        appendLine("    override fun get(kind: WidgetKind): WidgetDescriptor? = map[kind]")
        appendLine("}")
    }

    private fun List<String>.toSlotIdListLiteral(): String =
        if (isEmpty()) "emptyList()"
        else joinToString(prefix = "listOf(", postfix = ")") { "SlotId(\"${it.kotlinEscape()}\")" }

    private fun String.kotlinEscape(): String =
        replace("\\", "\\\\").replace("\"", "\\\"")
}

private data class WidgetEntry(
    val id: String,
    val displayName: String,
    val removable: Boolean,
    val slots: List<String>,
    val propsClassFqn: String?,
    val functionFqn: String,
    val containingFile: com.google.devtools.ksp.symbol.KSFile?,
)

class WidgetRegistryProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        WidgetRegistryProcessor(environment)
}
