package hivens.widget.processor

/**
 * One widget as the registry needs it, with every KSP type left behind. The
 * processor resolves symbols into these; everything downstream (collision
 * detection, source rendering) is a pure function of the list, which is the
 * half worth testing -- a wrong registry compiles fine and shows up only as a
 * widget that silently fails to draw.
 */
internal data class WidgetModel(
    val id: String,
    val displayName: String,
    val removable: Boolean,
    val slots: List<String>,
    /** FQN of the @Serializable props class, or null for a propless widget. */
    val propsClassFqn: String?,
    val functionFqn: String,
    /**
     * Whether the declaration takes the instance. A widget that reads neither
     * props nor per-instance state declares `fun Name()`, and the registry calls
     * it with no argument; the descriptor's own Render still receives the
     * instance, so nothing above the call site changes.
     */
    val takesInstance: Boolean = true,
    /** Service contracts from @ProvidesService, by FQN. */
    val provides: List<String> = emptyList(),
    /** Service contracts from @InjectService, by FQN. */
    val injects: List<String> = emptyList(),
    /** The default plane as JSON, or null for a widget that draws none. */
    val surfaceJson: String? = null,
)

/**
 * Injected contracts no widget in this build provides, keyed by the widget that
 * reads them.
 *
 * A consumer whose provider is absent is not a crash: the registry hands it
 * null every frame and the widget renders its disabled state forever. That is
 * correct behaviour for a provider the user has not placed yet, and
 * indistinguishable from a contract nothing can ever satisfy -- which is what
 * this separates.
 */
internal fun injectorsWithoutProvider(widgets: List<WidgetModel>): Map<WidgetModel, List<String>> {
    val provided = widgets.flatMapTo(HashSet()) { it.provides }
    return widgets
        .associateWith { widget -> widget.injects.filterNot { it in provided } }
        .filterValues { it.isNotEmpty() }
}

/**
 * Where the registry is emitted when a module does not say otherwise.
 *
 * These are defaults rather than constants because the name has to differ per
 * module: two modules both running the processor would otherwise emit the same
 * fully-qualified object, and only one of them could survive on a classpath.
 * A module carrying widgets overrides them through the KSP options
 * `widgetRegistryPackage` and `widgetRegistryName`.
 */
internal const val DEFAULT_GENERATED_PACKAGE = "hivens.widget.generated"
internal const val DEFAULT_GENERATED_NAME = "GeneratedWidgetRegistry"

/**
 * Ids declared more than once, keyed by id. The generated registry is a
 * `buildMap { put(...) }` and buildMap keeps the LAST put per key, so a shared
 * id would drop a widget with no diagnostic at all. The processor turns a
 * non-empty result into build errors instead.
 */
internal fun duplicateIds(widgets: List<WidgetModel>): Map<String, List<WidgetModel>> =
    widgets.groupBy { it.id }.filterValues { it.size > 1 }

/** Renders the registry object. Deterministic in the order of [widgets]. */
internal fun renderRegistry(
    widgets: List<WidgetModel>,
    packageName: String = DEFAULT_GENERATED_PACKAGE,
    objectName: String = DEFAULT_GENERATED_NAME,
): String = buildString {
    appendLine("// Generated by hivens.widget.processor.WidgetRegistryProcessor.")
    appendLine("// Do not edit -- changes are overwritten on the next build.")
    appendLine("package $packageName")
    appendLine()
    appendLine("import androidx.compose.runtime.Composable")
    appendLine("import hivens.widget.api.WidgetDescriptor")
    appendLine("import hivens.widget.api.WidgetRegistry")
    appendLine("import hivens.widget.model.SlotId")
    appendLine("import hivens.widget.model.WidgetInstance")
    appendLine("import hivens.widget.model.WidgetKind")
    // Serialization imports + the shared Json only when at least one widget
    // declares props or a default plane -- otherwise they would be unused and
    // warn on a build that has neither.
    val hasProps = widgets.any { it.propsClassFqn != null }
    val hasSurface = widgets.any { it.surfaceJson != null }
    if (hasSurface) appendLine("import hivens.widget.model.SurfaceSpec")
    if (hasProps || hasSurface) appendLine("import kotlinx.serialization.json.Json")
    if (hasProps) {
        appendLine("import kotlinx.serialization.KSerializer")
        appendLine("import kotlinx.serialization.json.JsonObject")
        appendLine("import kotlinx.serialization.json.jsonObject")
    }
    appendLine()
    appendLine("object $objectName : WidgetRegistry {")
    if (hasProps) {
        // encodeDefaults so the default-props baseline carries every field;
        // the editor overlays the instance's stored overrides.
        appendLine("    private val propsJson: Json = Json { encodeDefaults = true; ignoreUnknownKeys = true }")
    }
    if (hasSurface) {
        // The literals were decoded once at build time to check them; this decodes
        // them again at class-init, which is where a descriptor's constants belong.
        appendLine("    private val surfaceJson: Json = Json { ignoreUnknownKeys = true }")
    }
    appendLine("    private val map: Map<WidgetKind, WidgetDescriptor> = buildMap {")
    widgets.forEach { entry ->
        val kindLiteral = "WidgetKind(\"${entry.id.kotlinEscape()}\")"
        appendLine("        put($kindLiteral, object : WidgetDescriptor {")
        appendLine("            override val kind: WidgetKind = $kindLiteral")
        appendLine("            override val displayName: String = \"${entry.displayName.kotlinEscape()}\"")
        appendLine("            override val removable: Boolean = ${entry.removable}")
        appendLine("            override val slots: List<SlotId> = ${entry.slots.toSlotIdListLiteral()}")
        if (entry.provides.isNotEmpty()) {
            appendLine("            override val provides: Set<String> = ${entry.provides.toStringSetLiteral()}")
        }
        if (entry.injects.isNotEmpty()) {
            appendLine("            override val injects: Set<String> = ${entry.injects.toStringSetLiteral()}")
        }
        if (entry.surfaceJson != null) {
            appendLine("            override val defaultSurface: SurfaceSpec? =")
            appendLine("                surfaceJson.decodeFromString(SurfaceSpec.serializer(), \"${entry.surfaceJson.kotlinEscape()}\")")
        }
        if (entry.propsClassFqn != null) {
            val fqn = entry.propsClassFqn
            appendLine("            override val propsSerializer: KSerializer<*>? = $fqn.serializer()")
            appendLine("            override val defaultPropsJson: JsonObject =")
            appendLine("                propsJson.encodeToJsonElement($fqn.serializer(), $fqn()).jsonObject")
        }
        appendLine("            @Composable override fun Render(instance: WidgetInstance) {")
        appendLine("                ${entry.functionFqn}(${if (entry.takesInstance) "instance" else ""})")
        appendLine("            }")
        appendLine("        })")
    }
    appendLine("    }")
    appendLine()
    appendLine("    override fun all(): Map<WidgetKind, WidgetDescriptor> = map")
    appendLine("    override fun get(kind: WidgetKind): WidgetDescriptor? = map[kind]")
    appendLine("}")
    appendLine()
    appendLine("/**")
    appendLine(" * ServiceLoader entry point for a module loaded at runtime.")
    appendLine(" *")
    appendLine(" * The registry above is an object, so its constructor is private and")
    appendLine(" * ServiceLoader cannot instantiate it. This delegates to it and exists only")
    appendLine(" * to be named in META-INF/services.")
    appendLine(" */")
    appendLine("class $objectName$PROVIDER_SUFFIX : WidgetRegistry by $objectName")
}

/**
 * Name of the service the loader looks for. Written into the jar so discovery
 * needs no agreed class name, only an agreed interface.
 */
internal const val REGISTRY_SERVICE_FILE = "META-INF/services/hivens.widget.api.WidgetRegistry"

internal const val PROVIDER_SUFFIX = "Provider"

/** FQN of the generated provider, which is what the service file names. */
internal fun providerFqn(packageName: String, objectName: String): String =
    if (packageName.isEmpty()) "$objectName$PROVIDER_SUFFIX" else "$packageName.$objectName$PROVIDER_SUFFIX"

private fun List<String>.toStringSetLiteral(): String =
    joinToString(prefix = "setOf(", postfix = ")") { "\"${it.kotlinEscape()}\"" }

private fun List<String>.toSlotIdListLiteral(): String =
    if (isEmpty()) "emptyList()"
    else joinToString(prefix = "listOf(", postfix = ")") { "SlotId(\"${it.kotlinEscape()}\")" }

private fun String.kotlinEscape(): String =
    replace("\\", "\\\\").replace("\"", "\\\"")
